# Generated by Django 4.0.3 on 2022-03-19 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default=10.01, max_digits=5)),
                ('inventery', models.IntegerField(verbose_name='库存数')),
                ('sale_num', models.IntegerField(verbose_name='卖出数')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.publisher')),
            ],
        ),
    ]
